/// Generated by https://quicktype.io
use serde_derive::Deserialize;
use serde_derive::Serialize;
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct UserHomePageContentResponse {
    #[serde(rename = "data")]
    pub data: Option<Data>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Data {
    pub user: User,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct User {
    pub result: Result,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result {
    #[serde(rename = "__typename")]
    pub typename: String,
    #[serde(rename = "timeline_v2")]
    pub timeline_v2: TimelineV2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelineV2 {
    pub timeline: Timeline,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Timeline {
    pub instructions: Vec<Instruction>,
    pub metadata: Metadata2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Instruction {
    #[serde(rename = "type")]
    pub type_field: Option<String>,
    pub entry: Option<Entry>,
    #[serde(default)]
    pub entries: Option<Vec<Entry2>>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entry {
    pub entry_id: String,
    pub sort_index: String,
    pub content: Content,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Content {
    pub entry_type: String,
    #[serde(rename = "__typename")]
    pub typename: String,
    pub item_content: ItemContent,
    pub client_event_info: ClientEventInfo,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemContent {
    pub item_type: String,
    #[serde(rename = "__typename")]
    pub typename: String,
    #[serde(rename = "tweet_results")]
    pub tweet_results: TweetResults,
    pub tweet_display_type: String,
    pub social_context: SocialContext,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TweetResults {
    pub result: Result2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result2 {
    #[serde(rename = "__typename")]
    pub typename: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    pub core: Core,
    #[serde(rename = "unmention_data")]
    pub unmention_data: UnmentionData,
    #[serde(rename = "edit_control")]
    pub edit_control: EditControl,
    #[serde(rename = "is_translatable")]
    pub is_translatable: bool,
    pub views: Views,
    pub source: String,
    #[serde(rename = "note_tweet")]
    pub note_tweet: Option<NoteTweet>,
    pub legacy: Legacy2,
    #[serde(rename = "quick_promote_eligibility")]
    pub quick_promote_eligibility: QuickPromoteEligibility,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Core {
    #[serde(rename = "user_results")]
    pub user_results: UserResults,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserResults {
    pub result: Result3,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result3 {
    #[serde(rename = "__typename")]
    pub typename: String,
    pub id: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    #[serde(rename = "affiliates_highlighted_label")]
    pub affiliates_highlighted_label: AffiliatesHighlightedLabel,
    #[serde(rename = "has_graduated_access")]
    pub has_graduated_access: bool,
    #[serde(rename = "is_blue_verified")]
    pub is_blue_verified: bool,
    #[serde(rename = "profile_image_shape")]
    pub profile_image_shape: String,
    pub legacy: Legacy,
    #[serde(rename = "tipjar_settings")]
    pub tipjar_settings: TipjarSettings,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AffiliatesHighlightedLabel {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy {
    pub following: bool,
    #[serde(rename = "can_dm")]
    pub can_dm: bool,
    #[serde(rename = "can_media_tag")]
    pub can_media_tag: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "default_profile")]
    pub default_profile: bool,
    #[serde(rename = "default_profile_image")]
    pub default_profile_image: bool,
    pub description: String,
    pub entities: Entities,
    #[serde(rename = "fast_followers_count")]
    pub fast_followers_count: i64,
    #[serde(rename = "favourites_count")]
    pub favourites_count: i64,
    #[serde(rename = "followers_count")]
    pub followers_count: i64,
    #[serde(rename = "friends_count")]
    pub friends_count: i64,
    #[serde(rename = "has_custom_timelines")]
    pub has_custom_timelines: bool,
    #[serde(rename = "is_translator")]
    pub is_translator: bool,
    #[serde(rename = "listed_count")]
    pub listed_count: i64,
    pub location: String,
    #[serde(rename = "media_count")]
    pub media_count: i64,
    pub name: String,
    #[serde(rename = "normal_followers_count")]
    pub normal_followers_count: i64,
    #[serde(rename = "pinned_tweet_ids_str")]
    pub pinned_tweet_ids_str: Vec<String>,
    #[serde(rename = "possibly_sensitive")]
    pub possibly_sensitive: bool,
    #[serde(rename = "profile_banner_url")]
    pub profile_banner_url: Option<String>,
    #[serde(rename = "profile_image_url_https")]
    pub profile_image_url_https: String,
    #[serde(rename = "profile_interstitial_type")]
    pub profile_interstitial_type: String,
    #[serde(rename = "screen_name")]
    pub screen_name: String,
    #[serde(rename = "statuses_count")]
    pub statuses_count: i64,
    #[serde(rename = "translator_type")]
    pub translator_type: String,
    pub verified: bool,
    #[serde(rename = "want_retweets")]
    pub want_retweets: bool,
    #[serde(rename = "withheld_in_countries")]
    pub withheld_in_countries: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities {
    pub description: Description,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Description {
    pub urls: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TipjarSettings {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnmentionData {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EditControl {
    #[serde(rename = "edit_tweet_ids")]
    pub edit_tweet_ids: Vec<String>,
    #[serde(rename = "editable_until_msecs")]
    pub editable_until_msecs: String,
    #[serde(rename = "is_edit_eligible")]
    pub is_edit_eligible: bool,
    #[serde(rename = "edits_remaining")]
    pub edits_remaining: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Views {
    pub count: String,
    pub state: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteTweet {
    #[serde(rename = "is_expandable")]
    pub is_expandable: bool,
    #[serde(rename = "note_tweet_results")]
    pub note_tweet_results: NoteTweetResults,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteTweetResults {
    pub result: Result4,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result4 {
    pub id: String,
    pub text: String,
    #[serde(rename = "entity_set")]
    pub entity_set: EntitySet,
    pub richtext: Richtext,
    pub media: Media,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EntitySet {
    pub hashtags: Vec<Value>,
    pub symbols: Vec<Value>,
    pub urls: Vec<Value>,
    #[serde(rename = "user_mentions")]
    pub user_mentions: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Richtext {
    #[serde(rename = "richtext_tags")]
    pub richtext_tags: Vec<RichtextTag>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RichtextTag {
    #[serde(rename = "from_index")]
    pub from_index: i64,
    #[serde(rename = "to_index")]
    pub to_index: i64,
    #[serde(rename = "richtext_types")]
    pub richtext_types: Vec<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Media {
    #[serde(rename = "inline_media")]
    pub inline_media: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy2 {
    #[serde(rename = "bookmark_count")]
    pub bookmark_count: i64,
    pub bookmarked: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "conversation_id_str")]
    pub conversation_id_str: String,
    #[serde(rename = "display_text_range")]
    pub display_text_range: Vec<i64>,
    pub entities: Entities2,
    #[serde(rename = "favorite_count")]
    pub favorite_count: i64,
    pub favorited: bool,
    #[serde(rename = "full_text")]
    pub full_text: String,
    #[serde(rename = "is_quote_status")]
    pub is_quote_status: bool,
    pub lang: String,
    #[serde(rename = "quote_count")]
    pub quote_count: i64,
    #[serde(rename = "reply_count")]
    pub reply_count: i64,
    #[serde(rename = "retweet_count")]
    pub retweet_count: i64,
    pub retweeted: bool,
    #[serde(rename = "user_id_str")]
    pub user_id_str: String,
    #[serde(rename = "id_str")]
    pub id_str: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities2 {
    pub hashtags: Vec<Value>,
    pub symbols: Vec<Value>,
    pub timestamps: Vec<Value>,
    pub urls: Vec<Value>,
    #[serde(rename = "user_mentions")]
    pub user_mentions: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuickPromoteEligibility {
    pub eligibility: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SocialContext {
    #[serde(rename = "type")]
    pub type_field: Option<String>,
    pub context_type: String,
    pub text: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientEventInfo {
    pub component: String,
    pub element: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entry2 {
    pub entry_id: String,
    pub sort_index: String,
    pub content: Content2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Content2 {
    pub entry_type: String,
    #[serde(rename = "__typename")]
    pub typename: String,
    pub item_content: Option<ItemContent2>,
    pub client_event_info: Option<ClientEventInfo2>,
    #[serde(default)]
    pub items: Vec<Item>,
    pub display_type: Option<String>,
    pub header: Option<Header>,
    pub footer: Option<Footer>,
    pub metadata: Option<Metadata>,
    pub value: Option<String>,
    pub cursor_type: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemContent2 {
    pub item_type: String,
    #[serde(rename = "__typename")]
    pub typename: String,
    #[serde(rename = "tweet_results")]
    pub tweet_results: TweetResults2,
    pub tweet_display_type: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TweetResults2 {
    pub result: Option<Result5>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result5 {
    #[serde(rename = "__typename")]
    pub typename: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    pub core: Core2,
    #[serde(rename = "unmention_data")]
    pub unmention_data: UnmentionData2,
    #[serde(rename = "edit_control")]
    pub edit_control: EditControl2,
    #[serde(rename = "is_translatable")]
    pub is_translatable: bool,
    pub views: Views2,
    pub source: String,
    #[serde(rename = "quoted_status_result")]
    pub quoted_status_result: Option<QuotedStatusResult>,
    pub legacy: Legacy6,
    #[serde(rename = "quick_promote_eligibility")]
    pub quick_promote_eligibility: QuickPromoteEligibility2,
    pub card: Option<Card>,
    #[serde(rename = "note_tweet")]
    pub note_tweet: Option<NoteTweet3>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Core2 {
    #[serde(rename = "user_results")]
    pub user_results: Option<UserResults2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserResults2 {
    pub result: Result6,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result6 {
    #[serde(rename = "__typename")]
    pub typename: String,
    pub id: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    #[serde(rename = "affiliates_highlighted_label")]
    pub affiliates_highlighted_label: AffiliatesHighlightedLabel2,
    #[serde(rename = "has_graduated_access")]
    pub has_graduated_access: bool,
    #[serde(rename = "is_blue_verified")]
    pub is_blue_verified: bool,
    #[serde(rename = "profile_image_shape")]
    pub profile_image_shape: String,
    pub legacy: Legacy3,
    #[serde(rename = "tipjar_settings")]
    pub tipjar_settings: TipjarSettings2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AffiliatesHighlightedLabel2 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy3 {
    pub following: bool,
    #[serde(rename = "can_dm")]
    pub can_dm: bool,
    #[serde(rename = "can_media_tag")]
    pub can_media_tag: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "default_profile")]
    pub default_profile: bool,
    #[serde(rename = "default_profile_image")]
    pub default_profile_image: bool,
    pub description: String,
    pub entities: Entities3,
    #[serde(rename = "fast_followers_count")]
    pub fast_followers_count: i64,
    #[serde(rename = "favourites_count")]
    pub favourites_count: i64,
    #[serde(rename = "followers_count")]
    pub followers_count: i64,
    #[serde(rename = "friends_count")]
    pub friends_count: i64,
    #[serde(rename = "has_custom_timelines")]
    pub has_custom_timelines: bool,
    #[serde(rename = "is_translator")]
    pub is_translator: bool,
    #[serde(rename = "listed_count")]
    pub listed_count: i64,
    pub location: String,
    #[serde(rename = "media_count")]
    pub media_count: i64,
    pub name: String,
    #[serde(rename = "normal_followers_count")]
    pub normal_followers_count: i64,
    #[serde(rename = "pinned_tweet_ids_str")]
    pub pinned_tweet_ids_str: Vec<String>,
    #[serde(rename = "possibly_sensitive")]
    pub possibly_sensitive: bool,
    #[serde(rename = "profile_banner_url")]
    pub profile_banner_url: String,
    #[serde(rename = "profile_image_url_https")]
    pub profile_image_url_https: String,
    #[serde(rename = "profile_interstitial_type")]
    pub profile_interstitial_type: String,
    #[serde(rename = "screen_name")]
    pub screen_name: String,
    #[serde(rename = "statuses_count")]
    pub statuses_count: i64,
    #[serde(rename = "translator_type")]
    pub translator_type: String,
    pub verified: bool,
    #[serde(rename = "want_retweets")]
    pub want_retweets: bool,
    #[serde(rename = "withheld_in_countries")]
    pub withheld_in_countries: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities3 {
    pub description: Description2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Description2 {
    pub urls: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TipjarSettings2 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnmentionData2 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EditControl2 {
    #[serde(rename = "edit_tweet_ids")]
    pub edit_tweet_ids: Vec<String>,
    #[serde(rename = "editable_until_msecs")]
    pub editable_until_msecs: String,
    #[serde(rename = "is_edit_eligible")]
    pub is_edit_eligible: bool,
    #[serde(rename = "edits_remaining")]
    pub edits_remaining: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Views2 {
    pub count: String,
    pub state: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuotedStatusResult {
    pub result: Option<Result7>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result7 {
    #[serde(rename = "__typename")]
    pub typename: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    pub core: Core3,
    #[serde(rename = "unmention_data")]
    pub unmention_data: UnmentionData3,
    #[serde(rename = "edit_control")]
    pub edit_control: EditControl3,
    #[serde(rename = "is_translatable")]
    pub is_translatable: bool,
    pub views: Views3,
    pub source: String,
    pub legacy: Legacy5,
    pub quoted_ref_result: Option<QuotedRefResult>,
    #[serde(rename = "note_tweet")]
    pub note_tweet: Option<NoteTweet2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Core3 {
    #[serde(rename = "user_results")]
    pub user_results: UserResults3,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserResults3 {
    pub result: Result8,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result8 {
    #[serde(rename = "__typename")]
    pub typename: String,
    pub id: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    #[serde(rename = "affiliates_highlighted_label")]
    pub affiliates_highlighted_label: AffiliatesHighlightedLabel3,
    #[serde(rename = "has_graduated_access")]
    pub has_graduated_access: bool,
    #[serde(rename = "is_blue_verified")]
    pub is_blue_verified: bool,
    #[serde(rename = "profile_image_shape")]
    pub profile_image_shape: String,
    pub legacy: Legacy4,
    #[serde(rename = "tipjar_settings")]
    pub tipjar_settings: TipjarSettings3,
    pub professional: Option<Professional>,
    #[serde(rename = "super_follow_eligible")]
    pub super_follow_eligible: Option<bool>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AffiliatesHighlightedLabel3 {
    pub label: Option<Label>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Label {
    pub url: Option<Url>,
    pub badge: Badge,
    pub description: String,
    pub user_label_type: String,
    pub user_label_display_type: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url {
    pub url: Option<String>,
    pub url_type: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Badge {
    pub url: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy4 {
    pub following: bool,
    #[serde(rename = "can_dm")]
    pub can_dm: bool,
    #[serde(rename = "can_media_tag")]
    pub can_media_tag: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "default_profile")]
    pub default_profile: bool,
    #[serde(rename = "default_profile_image")]
    pub default_profile_image: bool,
    pub description: String,
    pub entities: Entities4,
    #[serde(rename = "fast_followers_count")]
    pub fast_followers_count: i64,
    #[serde(rename = "favourites_count")]
    pub favourites_count: i64,
    #[serde(rename = "followers_count")]
    pub followers_count: i64,
    #[serde(rename = "friends_count")]
    pub friends_count: i64,
    #[serde(rename = "has_custom_timelines")]
    pub has_custom_timelines: bool,
    #[serde(rename = "is_translator")]
    pub is_translator: bool,
    #[serde(rename = "listed_count")]
    pub listed_count: i64,
    pub location: String,
    #[serde(rename = "media_count")]
    pub media_count: i64,
    pub name: String,
    #[serde(rename = "normal_followers_count")]
    pub normal_followers_count: i64,
    #[serde(rename = "pinned_tweet_ids_str")]
    pub pinned_tweet_ids_str: Vec<String>,
    #[serde(rename = "possibly_sensitive")]
    pub possibly_sensitive: bool,
    #[serde(rename = "profile_banner_url")]
    pub profile_banner_url: Option<String>,
    #[serde(rename = "profile_image_url_https")]
    pub profile_image_url_https: String,
    #[serde(rename = "profile_interstitial_type")]
    pub profile_interstitial_type: String,
    #[serde(rename = "screen_name")]
    pub screen_name: String,
    #[serde(rename = "statuses_count")]
    pub statuses_count: i64,
    #[serde(rename = "translator_type")]
    pub translator_type: String,
    pub url: Option<String>,
    pub verified: bool,
    #[serde(rename = "want_retweets")]
    pub want_retweets: bool,
    #[serde(rename = "withheld_in_countries")]
    pub withheld_in_countries: Vec<Value>,
    #[serde(rename = "verified_type")]
    pub verified_type: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities4 {
    pub description: Description3,
    pub url: Option<Url3>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Description3 {
    pub urls: Vec<Url2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url2 {
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "expanded_url")]
    pub expanded_url: String,
    pub url: Option<String>,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url3 {
    pub urls: Vec<Url4>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url4 {
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "expanded_url")]
    pub expanded_url: String,
    pub url: Option<String>,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TipjarSettings3 {
    #[serde(rename = "is_enabled")]
    pub is_enabled: Option<bool>,
    #[serde(rename = "bitcoin_handle")]
    pub bitcoin_handle: Option<String>,
    #[serde(rename = "ethereum_handle")]
    pub ethereum_handle: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Professional {
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    #[serde(rename = "professional_type")]
    pub professional_type: String,
    pub category: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnmentionData3 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EditControl3 {
    #[serde(rename = "edit_tweet_ids")]
    pub edit_tweet_ids: Vec<String>,
    #[serde(rename = "editable_until_msecs")]
    pub editable_until_msecs: String,
    #[serde(rename = "is_edit_eligible")]
    pub is_edit_eligible: bool,
    #[serde(rename = "edits_remaining")]
    pub edits_remaining: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Views3 {
    pub count: String,
    pub state: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy5 {
    #[serde(rename = "bookmark_count")]
    pub bookmark_count: i64,
    pub bookmarked: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "conversation_id_str")]
    pub conversation_id_str: String,
    #[serde(rename = "display_text_range")]
    pub display_text_range: Vec<i64>,
    pub entities: Entities5,
    #[serde(rename = "favorite_count")]
    pub favorite_count: i64,
    pub favorited: bool,
    #[serde(rename = "full_text")]
    pub full_text: String,
    #[serde(rename = "is_quote_status")]
    pub is_quote_status: bool,
    pub lang: String,
    #[serde(rename = "quote_count")]
    pub quote_count: i64,
    #[serde(rename = "reply_count")]
    pub reply_count: i64,
    #[serde(rename = "retweet_count")]
    pub retweet_count: i64,
    pub retweeted: bool,
    #[serde(rename = "user_id_str")]
    pub user_id_str: String,
    #[serde(rename = "id_str")]
    pub id_str: String,
    #[serde(rename = "quoted_status_id_str")]
    pub quoted_status_id_str: Option<String>,
    #[serde(rename = "quoted_status_permalink")]
    pub quoted_status_permalink: Option<QuotedStatusPermalink>,
    #[serde(rename = "possibly_sensitive")]
    pub possibly_sensitive: Option<bool>,
    #[serde(rename = "possibly_sensitive_editable")]
    pub possibly_sensitive_editable: Option<bool>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities5 {
    pub hashtags: Vec<Value>,
    pub symbols: Vec<Symbol>,
    pub timestamps: Vec<Value>,
    pub urls: Vec<Url5>,
    #[serde(rename = "user_mentions")]
    pub user_mentions: Vec<UserMention>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Symbol {
    pub indices: Vec<i64>,
    pub text: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url5 {
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "expanded_url")]
    pub expanded_url: String,
    pub url: Option<String>,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserMention {
    #[serde(rename = "id_str")]
    pub id_str: String,
    pub name: String,
    #[serde(rename = "screen_name")]
    pub screen_name: String,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuotedStatusPermalink {
    pub url: Option<String>,
    pub expanded: String,
    pub display: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuotedRefResult {
    pub result: Result9,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result9 {
    #[serde(rename = "__typename")]
    pub typename: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteTweet2 {
    #[serde(rename = "is_expandable")]
    pub is_expandable: bool,
    #[serde(rename = "note_tweet_results")]
    pub note_tweet_results: NoteTweetResults2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteTweetResults2 {
    pub result: Result10,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result10 {
    pub id: String,
    pub text: String,
    #[serde(rename = "entity_set")]
    pub entity_set: EntitySet2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EntitySet2 {
    pub hashtags: Vec<Value>,
    pub symbols: Vec<Symbol2>,
    pub urls: Vec<Value>,
    #[serde(rename = "user_mentions")]
    pub user_mentions: Vec<UserMention2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Symbol2 {
    pub indices: Vec<i64>,
    pub text: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserMention2 {
    #[serde(rename = "id_str")]
    pub id_str: String,
    pub name: String,
    #[serde(rename = "screen_name")]
    pub screen_name: String,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy6 {
    #[serde(rename = "bookmark_count")]
    pub bookmark_count: i64,
    pub bookmarked: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "conversation_id_str")]
    pub conversation_id_str: String,
    #[serde(rename = "display_text_range")]
    pub display_text_range: Vec<i64>,
    pub entities: Entities6,
    #[serde(rename = "favorite_count")]
    pub favorite_count: i64,
    pub favorited: bool,
    #[serde(rename = "full_text")]
    pub full_text: String,
    #[serde(rename = "is_quote_status")]
    pub is_quote_status: bool,
    pub lang: String,
    #[serde(rename = "possibly_sensitive")]
    pub possibly_sensitive: Option<bool>,
    #[serde(rename = "possibly_sensitive_editable")]
    pub possibly_sensitive_editable: Option<bool>,
    #[serde(rename = "quote_count")]
    pub quote_count: i64,
    #[serde(rename = "quoted_status_id_str")]
    pub quoted_status_id_str: Option<String>,
    #[serde(rename = "quoted_status_permalink")]
    pub quoted_status_permalink: Option<QuotedStatusPermalink2>,
    #[serde(rename = "reply_count")]
    pub reply_count: i64,
    #[serde(rename = "retweet_count")]
    pub retweet_count: i64,
    pub retweeted: bool,
    #[serde(rename = "user_id_str")]
    pub user_id_str: String,
    #[serde(rename = "id_str")]
    pub id_str: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities6 {

    pub hashtags: Vec<Value>,
    pub symbols: Vec<Symbol3>,
    pub timestamps: Vec<Value>,
    pub urls: Vec<Url6>,
    #[serde(rename = "user_mentions")]
    pub user_mentions: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Symbol3 {
    pub indices: Vec<i64>,
    pub text: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url6 {
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "expanded_url")]
    pub expanded_url: String,
    pub url: Option<String>,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuotedStatusPermalink2 {
    pub url: Option<String>,
    pub expanded: String,
    pub display: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuickPromoteEligibility2 {
    pub eligibility: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Card {
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    pub legacy: Legacy7,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy7 {
    #[serde(rename = "binding_values")]
    pub binding_values: Vec<BindingValue>,
    #[serde(rename = "card_platform")]
    pub card_platform: CardPlatform,
    pub name: String,
    pub url: Option<String>,
    #[serde(rename = "user_refs_results")]
    pub user_refs_results: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BindingValue {
    pub key: String,
    pub value: Value,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Value {
    #[serde(rename = "image_value")]
    pub image_value: Option<ImageValue>,
    #[serde(rename = "type")]
    pub type_field: Option<String>,
    #[serde(rename = "string_value")]
    pub string_value: Option<String>,
    #[serde(rename = "scribe_key")]
    pub scribe_key: Option<String>,
    #[serde(rename = "image_color_value")]
    pub image_color_value: Option<ImageColorValue>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ImageValue {
    pub height: i64,
    pub width: i64,
    pub url: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ImageColorValue {
    pub palette: Vec<Palette>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Palette {
    pub rgb: Rgb,
    pub percentage: f64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Rgb {
    pub blue: i64,
    pub green: i64,
    pub red: i64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CardPlatform {
    pub platform: Platform,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Platform {
    pub audience: Audience,
    pub device: Device,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Audience {
    pub name: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Device {
    pub name: String,
    pub version: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteTweet3 {
    #[serde(rename = "is_expandable")]
    pub is_expandable: bool,
    #[serde(rename = "note_tweet_results")]
    pub note_tweet_results: NoteTweetResults3,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteTweetResults3 {
    pub result: Result11,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result11 {
    pub id: String,
    pub text: String,
    #[serde(rename = "entity_set")]
    pub entity_set: EntitySet3,
    pub richtext: Richtext2,
    pub media: Media2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EntitySet3 {
    pub hashtags: Vec<Value>,
    pub symbols: Vec<Symbol4>,
    pub urls: Vec<Url7>,
    #[serde(rename = "user_mentions")]
    pub user_mentions: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Symbol4 {
    pub indices: Vec<i64>,
    pub text: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url7 {
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "expanded_url")]
    pub expanded_url: String,
    pub url: Option<String>,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Richtext2 {
    #[serde(rename = "richtext_tags")]
    pub richtext_tags: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Media2 {
    #[serde(rename = "inline_media")]
    pub inline_media: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientEventInfo2 {
    pub component: String,
    pub element: Option<String>,
    pub details: Details,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Details {
    pub timelines_details: TimelinesDetails,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelinesDetails {
    pub injection_type: String,
    pub controller_data: String,
    pub source_data: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Item {
    pub entry_id: String,
    pub item: Item2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Item2 {
    pub item_content: ItemContent3,
    pub client_event_info: ClientEventInfo3,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemContent3 {
    pub item_type: String,
    #[serde(rename = "__typename")]
    pub typename: String,
    #[serde(rename = "tweet_results")]
    pub tweet_results: Option<TweetResults3>,
    pub tweet_display_type: Option<String>,
    #[serde(rename = "user_results")]
    pub user_results: Option<UserResults5>,
    pub user_display_type: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TweetResults3 {
    pub result: Result12,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result12 {
    #[serde(rename = "__typename")]
    pub typename: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    pub core: Core4,
    #[serde(rename = "unmention_data")]
    pub unmention_data: UnmentionData4,
    #[serde(rename = "edit_control")]
    pub edit_control: EditControl4,
    #[serde(rename = "is_translatable")]
    pub is_translatable: bool,
    pub views: Views4,
    pub source: String,
    #[serde(rename = "note_tweet")]
    pub note_tweet: Option<NoteTweet4>,
    pub legacy: Legacy9,
    #[serde(rename = "quick_promote_eligibility")]
    pub quick_promote_eligibility: QuickPromoteEligibility3,
    pub card: Option<Card2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Core4 {
    #[serde(rename = "user_results")]
    pub user_results: UserResults4,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserResults4 {
    pub result: Result13,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result13 {
    #[serde(rename = "__typename")]
    pub typename: String,
    pub id: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    #[serde(rename = "affiliates_highlighted_label")]
    pub affiliates_highlighted_label: AffiliatesHighlightedLabel4,
    #[serde(rename = "has_graduated_access")]
    pub has_graduated_access: bool,
    #[serde(rename = "is_blue_verified")]
    pub is_blue_verified: bool,
    #[serde(rename = "profile_image_shape")]
    pub profile_image_shape: String,
    pub legacy: Legacy8,
    #[serde(rename = "tipjar_settings")]
    pub tipjar_settings: TipjarSettings4,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AffiliatesHighlightedLabel4 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy8 {
    pub following: bool,
    #[serde(rename = "can_dm")]
    pub can_dm: bool,
    #[serde(rename = "can_media_tag")]
    pub can_media_tag: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "default_profile")]
    pub default_profile: bool,
    #[serde(rename = "default_profile_image")]
    pub default_profile_image: bool,
    pub description: String,
    pub entities: Entities7,
    #[serde(rename = "fast_followers_count")]
    pub fast_followers_count: i64,
    #[serde(rename = "favourites_count")]
    pub favourites_count: i64,
    #[serde(rename = "followers_count")]
    pub followers_count: i64,
    #[serde(rename = "friends_count")]
    pub friends_count: i64,
    #[serde(rename = "has_custom_timelines")]
    pub has_custom_timelines: bool,
    #[serde(rename = "is_translator")]
    pub is_translator: bool,
    #[serde(rename = "listed_count")]
    pub listed_count: i64,
    pub location: String,
    #[serde(rename = "media_count")]
    pub media_count: i64,
    pub name: String,
    #[serde(rename = "normal_followers_count")]
    pub normal_followers_count: i64,
    #[serde(rename = "pinned_tweet_ids_str")]
    pub pinned_tweet_ids_str: Vec<String>,
    #[serde(rename = "possibly_sensitive")]
    pub possibly_sensitive: bool,
    #[serde(rename = "profile_banner_url")]
    pub profile_banner_url: Option<String>,
    #[serde(rename = "profile_image_url_https")]
    pub profile_image_url_https: String,
    #[serde(rename = "profile_interstitial_type")]
    pub profile_interstitial_type: String,
    #[serde(rename = "screen_name")]
    pub screen_name: String,
    #[serde(rename = "statuses_count")]
    pub statuses_count: i64,
    #[serde(rename = "translator_type")]
    pub translator_type: String,
    pub verified: bool,
    #[serde(rename = "want_retweets")]
    pub want_retweets: bool,
    #[serde(rename = "withheld_in_countries")]
    pub withheld_in_countries: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities7 {
    pub description: Description4,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Description4 {
    pub urls: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TipjarSettings4 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnmentionData4 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EditControl4 {
    #[serde(rename = "edit_tweet_ids")]
    pub edit_tweet_ids: Vec<String>,
    #[serde(rename = "editable_until_msecs")]
    pub editable_until_msecs: String,
    #[serde(rename = "is_edit_eligible")]
    pub is_edit_eligible: bool,
    #[serde(rename = "edits_remaining")]
    pub edits_remaining: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Views4 {
    pub count: String,
    pub state: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteTweet4 {
    #[serde(rename = "is_expandable")]
    pub is_expandable: bool,
    #[serde(rename = "note_tweet_results")]
    pub note_tweet_results: NoteTweetResults4,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NoteTweetResults4 {
    pub result: Result14,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result14 {
    pub id: String,
    pub text: String,
    #[serde(rename = "entity_set")]
    pub entity_set: EntitySet4,
    pub richtext: Richtext3,
    pub media: Media3,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EntitySet4 {
    pub hashtags: Vec<Value>,
    pub symbols: Vec<Value>,
    pub urls: Vec<Value>,
    #[serde(rename = "user_mentions")]
    pub user_mentions: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Richtext3 {
    #[serde(rename = "richtext_tags")]
    pub richtext_tags: Vec<RichtextTag2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RichtextTag2 {
    #[serde(rename = "from_index")]
    pub from_index: i64,
    #[serde(rename = "to_index")]
    pub to_index: i64,
    #[serde(rename = "richtext_types")]
    pub richtext_types: Vec<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Media3 {
    #[serde(rename = "inline_media")]
    pub inline_media: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy9 {
    #[serde(rename = "bookmark_count")]
    pub bookmark_count: i64,
    pub bookmarked: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "conversation_id_str")]
    pub conversation_id_str: String,
    #[serde(rename = "display_text_range")]
    pub display_text_range: Vec<i64>,
    pub entities: Entities8,
    #[serde(rename = "favorite_count")]
    pub favorite_count: i64,
    pub favorited: bool,
    #[serde(rename = "full_text")]
    pub full_text: String,
    #[serde(rename = "is_quote_status")]
    pub is_quote_status: bool,
    pub lang: String,
    #[serde(rename = "quote_count")]
    pub quote_count: i64,
    #[serde(rename = "reply_count")]
    pub reply_count: i64,
    #[serde(rename = "retweet_count")]
    pub retweet_count: i64,
    pub retweeted: bool,
    #[serde(rename = "user_id_str")]
    pub user_id_str: String,
    #[serde(rename = "id_str")]
    pub id_str: String,
    #[serde(rename = "in_reply_to_screen_name")]
    pub in_reply_to_screen_name: Option<String>,
    #[serde(rename = "in_reply_to_status_id_str")]
    pub in_reply_to_status_id_str: Option<String>,
    #[serde(rename = "in_reply_to_user_id_str")]
    pub in_reply_to_user_id_str: Option<String>,
    #[serde(rename = "possibly_sensitive")]
    pub possibly_sensitive: Option<bool>,
    #[serde(rename = "possibly_sensitive_editable")]
    pub possibly_sensitive_editable: Option<bool>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities8 {
    pub hashtags: Vec<Value>,
    pub symbols: Vec<Value>,
    pub timestamps: Vec<Value>,
    pub urls: Vec<Url8>,
    #[serde(rename = "user_mentions")]
    pub user_mentions: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url8 {
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "expanded_url")]
    pub expanded_url: String,
    pub url: Option<String>,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuickPromoteEligibility3 {
    pub eligibility: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Card2 {
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    pub legacy: Legacy10,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy10 {
    #[serde(rename = "binding_values")]
    pub binding_values: Vec<BindingValue2>,
    #[serde(rename = "card_platform")]
    pub card_platform: CardPlatform2,
    pub name: String,
    pub url: Option<String>,
    #[serde(rename = "user_refs_results")]
    pub user_refs_results: Vec<UserRefsResult>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BindingValue2 {
    pub key: String,
    pub value: Value2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Value2 {
    #[serde(rename = "string_value")]
    pub string_value: Option<String>,
    #[serde(rename = "type")]
    pub type_field: Option<String>,
    #[serde(rename = "image_value")]
    pub image_value: Option<ImageValue2>,
    #[serde(rename = "scribe_key")]
    pub scribe_key: Option<String>,
    #[serde(rename = "user_value")]
    pub user_value: Option<UserValue>,
    #[serde(rename = "image_color_value")]
    pub image_color_value: Option<ImageColorValue2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ImageValue2 {
    pub height: i64,
    pub width: i64,
    pub url: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserValue {
    #[serde(rename = "id_str")]
    pub id_str: String,
    pub path: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ImageColorValue2 {
    pub palette: Vec<Palette2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Palette2 {
    pub rgb: Rgb2,
    pub percentage: f64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Rgb2 {
    pub blue: i64,
    pub green: i64,
    pub red: i64,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CardPlatform2 {
    pub platform: Platform2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Platform2 {
    pub audience: Audience2,
    pub device: Device2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Audience2 {
    pub name: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Device2 {
    pub name: String,
    pub version: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserRefsResult {
    pub result: Result15,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result15 {
    #[serde(rename = "__typename")]
    pub typename: String,
    pub id: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    #[serde(rename = "affiliates_highlighted_label")]
    pub affiliates_highlighted_label: AffiliatesHighlightedLabel5,
    #[serde(rename = "has_graduated_access")]
    pub has_graduated_access: bool,
    #[serde(rename = "is_blue_verified")]
    pub is_blue_verified: bool,
    #[serde(rename = "profile_image_shape")]
    pub profile_image_shape: String,
    pub legacy: Legacy11,
    pub professional: Professional2,
    #[serde(rename = "tipjar_settings")]
    pub tipjar_settings: TipjarSettings5,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AffiliatesHighlightedLabel5 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy11 {
    pub following: bool,
    #[serde(rename = "can_dm")]
    pub can_dm: bool,
    #[serde(rename = "can_media_tag")]
    pub can_media_tag: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "default_profile")]
    pub default_profile: bool,
    #[serde(rename = "default_profile_image")]
    pub default_profile_image: bool,
    pub description: String,
    pub entities: Entities9,
    #[serde(rename = "fast_followers_count")]
    pub fast_followers_count: i64,
    #[serde(rename = "favourites_count")]
    pub favourites_count: i64,
    #[serde(rename = "followers_count")]
    pub followers_count: i64,
    #[serde(rename = "friends_count")]
    pub friends_count: i64,
    #[serde(rename = "has_custom_timelines")]
    pub has_custom_timelines: bool,
    #[serde(rename = "is_translator")]
    pub is_translator: bool,
    #[serde(rename = "listed_count")]
    pub listed_count: i64,
    pub location: String,
    #[serde(rename = "media_count")]
    pub media_count: i64,
    pub name: String,
    #[serde(rename = "normal_followers_count")]
    pub normal_followers_count: i64,
    #[serde(rename = "pinned_tweet_ids_str")]
    pub pinned_tweet_ids_str: Vec<String>,
    #[serde(rename = "possibly_sensitive")]
    pub possibly_sensitive: bool,
    #[serde(rename = "profile_banner_url")]
    pub profile_banner_url: Option<String>,
    #[serde(rename = "profile_image_url_https")]
    pub profile_image_url_https: String,
    #[serde(rename = "profile_interstitial_type")]
    pub profile_interstitial_type: String,
    #[serde(rename = "screen_name")]
    pub screen_name: String,
    #[serde(rename = "statuses_count")]
    pub statuses_count: i64,
    #[serde(rename = "translator_type")]
    pub translator_type: String,
    pub url: Option<String>,
    pub verified: bool,
    #[serde(rename = "want_retweets")]
    pub want_retweets: bool,
    #[serde(rename = "withheld_in_countries")]
    pub withheld_in_countries: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities9 {
    pub description: Description5,
    pub url: Url9,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Description5 {
    pub urls: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url9 {
    pub urls: Vec<Url10>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url10 {
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "expanded_url")]
    pub expanded_url: String,
    pub url: Option<String>,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Professional2 {
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    #[serde(rename = "professional_type")]
    pub professional_type: String,
    pub category: Vec<Category>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Category {
    pub id: i64,
    pub name: String,
    #[serde(rename = "icon_name")]
    pub icon_name: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TipjarSettings5 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserResults5 {
    pub result: Result16,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Result16 {
    #[serde(rename = "__typename")]
    pub typename: String,
    pub id: String,
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    #[serde(rename = "affiliates_highlighted_label")]
    pub affiliates_highlighted_label: AffiliatesHighlightedLabel6,
    #[serde(rename = "has_graduated_access")]
    pub has_graduated_access: bool,
    #[serde(rename = "is_blue_verified")]
    pub is_blue_verified: bool,
    #[serde(rename = "profile_image_shape")]
    pub profile_image_shape: String,
    pub legacy: Legacy12,
    pub professional: Option<Professional3>,
    #[serde(rename = "tipjar_settings")]
    pub tipjar_settings: TipjarSettings6,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AffiliatesHighlightedLabel6 {
    pub label: Option<Label2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Label2 {
    pub url: Url11,
    pub badge: Badge2,
    pub description: String,
    pub user_label_type: String,
    pub user_label_display_type: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url11 {
    pub url: Option<String>,
    pub url_type: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Badge2 {
    pub url: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Legacy12 {
    pub following: bool,
    #[serde(rename = "can_dm")]
    pub can_dm: bool,
    #[serde(rename = "can_media_tag")]
    pub can_media_tag: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "default_profile")]
    pub default_profile: bool,
    #[serde(rename = "default_profile_image")]
    pub default_profile_image: bool,
    pub description: String,
    pub entities: Entities10,
    #[serde(rename = "fast_followers_count")]
    pub fast_followers_count: i64,
    #[serde(rename = "favourites_count")]
    pub favourites_count: i64,
    #[serde(rename = "followers_count")]
    pub followers_count: i64,
    #[serde(rename = "friends_count")]
    pub friends_count: i64,
    #[serde(rename = "has_custom_timelines")]
    pub has_custom_timelines: bool,
    #[serde(rename = "is_translator")]
    pub is_translator: bool,
    #[serde(rename = "listed_count")]
    pub listed_count: i64,
    pub location: String,
    #[serde(rename = "media_count")]
    pub media_count: i64,
    pub name: String,
    #[serde(rename = "normal_followers_count")]
    pub normal_followers_count: i64,
    #[serde(rename = "pinned_tweet_ids_str")]
    pub pinned_tweet_ids_str: Vec<String>,
    #[serde(rename = "possibly_sensitive")]
    pub possibly_sensitive: bool,
    #[serde(rename = "profile_banner_url")]
    pub profile_banner_url: Option<String>,
    #[serde(rename = "profile_image_url_https")]
    pub profile_image_url_https: String,
    #[serde(rename = "profile_interstitial_type")]
    pub profile_interstitial_type: String,
    #[serde(rename = "screen_name")]
    pub screen_name: String,
    #[serde(rename = "statuses_count")]
    pub statuses_count: i64,
    #[serde(rename = "translator_type")]
    pub translator_type: String,
    pub url: Option<String>,
    pub verified: bool,
    #[serde(rename = "want_retweets")]
    pub want_retweets: bool,
    #[serde(rename = "withheld_in_countries")]
    pub withheld_in_countries: Vec<Value>,
    #[serde(rename = "verified_type")]
    pub verified_type: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Entities10 {
    pub description: Description6,
    pub url: Url12,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Description6 {
    pub urls: Vec<Value>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url12 {
    pub urls: Vec<Url13>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Url13 {
    #[serde(rename = "display_url")]
    pub display_url: String,
    #[serde(rename = "expanded_url")]
    pub expanded_url: String,
    pub url: Option<String>,
    pub indices: Vec<i64>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Professional3 {
    #[serde(rename = "rest_id")]
    pub rest_id: String,
    #[serde(rename = "professional_type")]
    pub professional_type: String,
    pub category: Vec<Category2>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Category2 {
    pub id: i64,
    pub name: String,
    #[serde(rename = "icon_name")]
    pub icon_name: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TipjarSettings6 {
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ClientEventInfo3 {
    pub component: String,
    pub element: String,
    pub details: Details2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Details2 {
    pub timelines_details: TimelinesDetails2,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TimelinesDetails2 {
    pub injection_type: String,
    pub controller_data: String,
    pub source_data: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Header {
    pub display_type: String,
    pub text: String,
    pub sticky: bool,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Footer {
    pub display_type: String,
    pub text: String,
    pub landing_url: LandingUrl,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LandingUrl {
    pub url: Option<String>,
    pub url_type: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Metadata {
    pub conversation_metadata: ConversationMetadata,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConversationMetadata {
    pub all_tweet_ids: Vec<String>,
    pub enable_deduplication: bool,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Metadata2 {
    pub scribe_config: ScribeConfig,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ScribeConfig {
    pub page: String,
}
